#!/usr/bin/env bash
# PreToolUse hook (Edit|Write): denies any change to the generated `plugins`
# array of .claude-plugin/marketplace.json. Other top-level fields stay
# editable. Pure: no side effects. See docs/decisions/adr-0002-project-hooks.md.
set -euo pipefail

command -v jq >/dev/null 2>&1 || exit 0

input="$(cat)"
root="${CLAUDE_PROJECT_DIR:-$(jq -r '.cwd // empty' <<<"${input}")}"
root="${root:-${PWD}}"
catalog="${root}/.claude-plugin/marketplace.json"

file_path="$(jq -r '.tool_input.file_path // empty' <<<"${input}")"
[[ -n "${file_path}" && -f "${catalog}" ]] || exit 0

# Resolve `..` and symlinks in the directory part before comparing paths.
target_dir="$(cd "$(dirname "${file_path}")" 2>/dev/null && pwd -P)" || exit 0
catalog_dir="$(cd "$(dirname "${catalog}")" && pwd -P)"
[[ "${target_dir}/$(basename "${file_path}")" == "${catalog_dir}/$(basename "${catalog}")" ]] || exit 0

# Simulates the edit and prints "deny" only when `plugins` would change.
# split/join is a literal (non-regex) replacement, matching the Edit tool.
verdict="$(
  jq -r --rawfile current "${catalog}" '
    def plugins: try (fromjson | .plugins | tojson) catch "INVALID";
    .tool_input as $t
    | (if .tool_name == "Write" then $t.content // ""
       elif .tool_name == "Edit" and ($current | contains($t.old_string)) then
         if $t.replace_all then $current | split($t.old_string) | join($t.new_string)
         else ($current | split($t.old_string)) as $p
           | $p[0] + $t.new_string + ($p[1:] | join($t.old_string))
         end
       else null end) as $next
    | if $next == null then "allow"
      else ($next | plugins) as $after
        | if $after == "INVALID" or $after == ($current | plugins) then "allow" else "deny" end
      end
  ' <<<"${input}"
)"

[[ "${verdict}" == "deny" ]] || exit 0

jq -n '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "deny",
    permissionDecisionReason: "The `plugins` array in .claude-plugin/marketplace.json is generated by scripts/marketplace/generate_marketplace.py and must not be hand-edited. Change plugins/<name>/.claude-plugin/plugin.json instead, then run `make generate`. Other top-level fields of marketplace.json remain editable."
  }
}'
